# Change these first
owner: theodorlindberg # Your GitHub organization or username, where this repository lives
repo: futf-uptime # The name of this repository

sites:
  - name: Uptime
    url: https://uptime.futf.se
  - name: Hemisda
    url: https://futf.se
  - name: Mattermost
    url: https://mattermost.futf.se
  - name: Vaultwarden
    url: https://vault.futf.se
  - name: Forms
    url: https://forms.futf.se
  - name: Arbetsmarknad
    url: https://arbetsmarknad.futf.se
  - name: TeFAT
    url: https://tefat.futf.se
  - name: Link
    url: https://link.futf.se/gdpr
#  - name: Vote
#    url: https://vote.futf.se
    
  - name: FUTF Minecraft
    url: mc.futf.se
    port: 25565
    check: "tcp-ping"
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.futf.se
  #baseUrl: /futf-uptime
  logoUrl: https://futf.se/favicon-futf.ico
  name: FUTF Status
  introTitle: "Föreningen Uppsala Tekniska Fysiker"
  introMessage: "Status för föreningens hemsidor och IT tjänster, kontakta **sysadmin@futf.se** vid problem. Se [uptime.futf.se](https://uptime.futf.se/status/web) för status i realtid"
  navbar:
    - title: Kontakt
      href: mailto:sysadmin@futf.se
    - title: Uptime
      href: https://uptime.futf.se/status/web
    - title: Hemsida
      href: https://futf.se

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
